name: image2hashtag
description: AI tabanlı bir paket. Verilen bir görsel için sosyal medya hashtag önerileri üretir.
version: 0.0.1
homepage: https://github.com/bilalozcan

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
